[package]
name = "example_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsim = { git = "https://github.com/PatatasDelPapa/RustSim.git", branch = "main" }